server:
    port: 8083
    error.include-message: always
springdoc:
    swagger-ui:
        path: /swagger-ui.html
spring:
    jpa:
        properties.hibernate.dialect: org.hibernate.dialect.MySQL55Dialect
        hibernate.ddl-auto: validate
    flyway.baseline-on-migrate: true
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/llib
        username: root
        password: nastia0403
    main:
        allow-circular-references: true